- src/abaqus/Field/AnalyticalField.py
- src/abaqus/Field/OdbMeshRegionData.py
Remove transformationType argument for OdbMeshRegionData
> Remove transformationType argument for OdbMeshRegionData

- src/abaqus/Odb/OdbMeshElement.py
> Add OdbMeshElement.getNormal

- src/abaqus/Section/SectionLayer.py
Remove SectionLayer.thicknessType and SectionLayer.thicknessField
> Remove SectionLayer.thicknessType and SectionLayer.thicknessField

- src/abaqus/Sketcher/ConstrainedSketchDimension/DistanceDimension.py
- src/abaqus/Sketcher/ConstrainedSketchGeometry/ArcByCenterEnds.py
- [ArcByCenterEnds add direction argument](https://github.com/haiiliin/abqpy/commit/8cfd2423c510e8194e8917a72a11ba20784b96ab)
- [DistanceDimension argument vertex2 renamed to entity2](https://github.com/haiiliin/abqpy/commit/a7e4683b14ea512c11abb7f3bc1c8cc4aa5e977c)
> Sketcher API Changes

- src/abaqus/PredefinedField/PredefinedFieldModel.py
- src/abaqus/PredefinedField/Stress.py
> Add Stress predefined field

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2017a4

- src/abaqus/Job/Job.py
- src/abaqus/Job/JobFromInputFile.py
- src/abaqus/Job/ModelJob.py
Update default value of parallelizationMethodExplicit to LOOP
> Update default value of parallelizationMethodExplicit to LOOP

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2017a5

- .mergify.yml
> Backport to specific versions

- .mergify.yml
Update backport pull request title
> Update backport pull request title

- .mergify.yml
Fix bugs in backport pull request titles
> Fix bugs in backport pull request titles

- .github/release-drafter-v2016.yml
- .github/release-drafter-v2017.yml
- .github/release-drafter-v2018.yml
- .github/release-drafter-v2019.yml
- .github/release-drafter-v2020.yml
- .github/release-drafter-v2021.yml
- .github/release-drafter-v2022.yml
- .github/release-drafter.yml
Update release drafter on the next version
> Update release drafter on the next version

- .github/release-drafter-v2016.yml
- .github/release-drafter-v2017.yml
- .github/release-drafter-v2018.yml
- .github/release-drafter-v2019.yml
- .github/release-drafter-v2020.yml
- .github/release-drafter-v2021.yml
- .github/release-drafter-v2022.yml
- .github/release-drafter.yml
> Update version template

- .github/release-drafter-v2016.yml
- .github/release-drafter-v2017.yml
- .github/release-drafter-v2018.yml
- .github/release-drafter-v2019.yml
- .github/release-drafter-v2020.yml
- .github/release-drafter-v2021.yml
- .github/release-drafter-v2022.yml
- .github/release-drafter.yml
- .mergify.yml
Add backport label to backport pull requests
> Add backport label to backport pull requests

- src/abaqus/Assembly/AssemblyBase.py
- src/abaqus/Part/AcisFile.py
- src/abaqus/Part/PartBase.py
- src/abaqus/Sketcher/ConstrainedSketch.py
Update fileName docs of writeAcisFile
> Update fileName docs of writeAcisFile

- src/abaqus/Assembly/AssemblyBase.py
Fix fileName docs of writeAcisFile, see also #53.
> Fix fileName docs of writeAcisFile

- src/abaqus/BasicGeometry/CellArray.py
- src/abaqus/BasicGeometry/FaceArray.py
Remove CellArray.getExteriorFaces and FaceArray.getExteriorEdges
> Remove CellArray.getExteriorFaces and FaceArray.getExteriorEdges

- src/abaqus/BasicGeometry/Cell.py
- src/abaqus/BasicGeometry/Face.py
> Remove getCADAttributes

- src/abaqus/EngineeringFeature/EngineeringFeature.py
- src/abaqus/EngineeringFeature/XFEMCrack.py
Remove autoDetectValue argument for XFEMCrack
> Remove autoDetectValue argument for XFEMCrack

- src/abaqus/FieldReport/FieldReportSession.py
- src/abaqus/FieldReport/writeFieldReport.py
Remove write field report step frame
> Remove stepFrame argument for writeFieldReport

- src/abaqus/FieldReport/FieldReportSession.py
Fix FieldReportSession methods' names
> Fix FieldReportSession methods' names

- src/abaqus/Load/BoltLoad.py
Remove  bolt load pre ten sec part level
> Remove preTenSecPartLevel attribute for BoltLoad

- src/abaqus/Load/BoltLoad.py
- src/abaqus/Load/LoadModel.py
Add preTenSecPartLevel argument for BoltLoad
> Add preTenSecPartLevel argument for BoltLoad

- docs/source/reference/mdb/model/material.rst
- src/abaqus/Material/Material.py
- src/abaqus/Material/MaterialBase.py
- src/abaqus/Material/Multiscale/MeanFieldHomogenization.py
- src/abaqus/Material/Multiscale/MeanFieldInclusion.py
- src/abaqus/Material/Multiscale/MeanFieldMatrix.py
- src/abaqus/Material/Multiscale/MeanFieldVoid.py
Add multiscale mean field material
> Add multiscale mean field material

- src/abaqus/Mesh/MeshElementArray.py
Add getExteriorEdges and getExteriorFaces for MeshElementArray
> Add getExteriorEdges and getExteriorFaces for MeshElementArray

- src/abaqus/Mesh/MesherOptions.py
Add guiPreferredElements for MesherOptions
> Add guiPreferredElements for MesherOptions

- src/abaqus/OdbDisplay/ContourOptions.py
- src/abaqus/OdbDisplay/ViewCut.py
> Update odb display options

- src/abaqus/PredefinedField/Field.py
- src/abaqus/PredefinedField/FieldState.py
- src/abaqus/PredefinedField/PredefinedFieldModel.py
> Add Field and FieldState

- src/abaqus/Region/Set.py
Add unsorted argument for Set.SetFromNodeLabels
> Add unsorted argument for Set.SetFromNodeLabels

- src/abaqus/Section/HomogeneousSolidSection.py
- src/abaqus/Section/SectionModel.py
Update docs of HomogeneousSolidSection.thickness
> Update docs of HomogeneousSolidSection.thickness

- src/abaqus/Session/Drawing.py
Add depthTest argument for Drawing
> Add depthTest argument for Drawing

- src/abaqus/UtilityAndView/Method.py
Remove removeCallback for V2017 and V2016
> Remove removeCallback for V2017 and V2016

- src/abaqus/XY/XYData.py
Add removeDuplicateXYPairs and includeAllElements for XYDataFromPath
> Add removeDuplicateXYPairs and includeAllElements for XYDataFromPath

- src/abaqus/Odb/UserDataBase.py
- src/abaqus/XY/AxisData.py
- src/abaqus/XY/QuantityType.py
- src/abaqus/XY/XYPlot.py
- src/abaqus/XY/XYSession.py
Backport QuantityType to V2017 and V2016
> Backport QuantityType to V2017 and V2016

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update to v2018a6

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update to v2017a6

- src/abaqus/Interaction/FluidInflator.py
- src/abaqus/Interaction/FluidInflatorProperty.py
- src/abaqus/Interaction/FluidInflatorState.py
- src/abaqus/Interaction/InteractionModel.py
- src/abaqus/Interaction/InteractionPropertyModel.py
> Add FluidInflator Interaction

- src/abaqus/DisplayGroup/LeafFromConstraintNames.py
- src/displayGroupMdbToolset.py
> Add LeafFromConstraintNames

- src/abaqus/Assembly/ModelInstance.py
> Add ModelInstance.replace

- src/abaqus/Assembly/ModelInstance.py
> Revert "Add ModelInstance.replace"

- src/abaqus/Interaction/SurfaceToSurfaceContactStd.py
Remove handedness and normalAdjustment for V2016-V2018
> Remove handedness and normalAdjustment for V2016-V2018

- src/abaqus/Mesh/ElemType.py
Add numFourierModes and nodeOffset for ElemType
> Add numFourierModes and nodeOffset for ElemType

- src/abaqus/Odb/OdbAssembly.py
- src/abaqus/Odb/OdbInstance.py
- src/abaqus/Odb/OdbStep.py
Rename OdbRigidBody to RigidBody, OdbLoadCase to LoadCase
> Rename OdbRigidBody to RigidBody, OdbLoadCase to LoadCase

- src/abaqus/Odb/OdbInstance.py
Remove OdbRigidBody in OdbInstance
> Remove OdbRigidBody in OdbInstance

- src/abaqus/Odb/OdbAssembly.py
- src/abaqus/Odb/OdbAssemblyBase.py
- src/abaqus/Odb/OdbInstanceBase.py
- src/abaqus/Odb/OdbPart.py
Remove analyticSurface for RigidBody for V2016-V2018
> Remove analyticSurface for RigidBody for V2016-V2018

- src/abaqus/OdbDisplay/ContourOptions.py
Add legendHideOutsideLimits for ContourOptions
> Add legendHideOutsideLimits for ContourOptions

- src/abaqus/Optimization/BeadTask.py
- src/abaqus/Optimization/OptimizationTaskModel.py
- src/abaqus/Optimization/ShapeTask.py
- src/abaqus/Optimization/SizingTask.py
- src/abaqus/Optimization/TopologyTask.py
> Remove abaqus sensitivities for V2016-V2018

- src/abaqus/Optimization/BeadTask.py
- src/abaqus/Optimization/OptimizationTaskModel.py
- src/abaqus/Optimization/ShapeTask.py
- src/abaqus/Optimization/SizingTask.py
- src/abaqus/Optimization/TopologyTask.py
Add abaqusSensitivities argument for optimization tasks
> Add abaqusSensitivities argument for optimization tasks

- src/abaqus/Optimization/OptimizationTask.py
- src/abaqus/Optimization/TopologyOverhangControl.py
Add TopologyOverhangControl optimization task
> Add TopologyOverhangControl optimization task

- src/abaqus/Optimization/TopologyTask.py
Add abaqusSensitivities for TopologyTask for V2016-V2018
> Add abaqusSensitivities for TopologyTask for V2016-V2018

- src/abaqus/PlotOptions/BasicOptions.py
Update docs for numericForm of BasicOptions
> Update docs for numericForm of BasicOptions

- src/abaqus/PlotOptions/BasicOptions.py
V2018 basic options numeric form
> Update docs for numericForm of BasicOptions in V2016-V2018

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2019a7

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2016a7

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2017a7

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2018a7

- src/abaqus/Assembly/AssemblyBase.py
Delete coordinates argument and update nodes argument for Assembly
> Delete coordinates argument and update nodes argument for Assembly

- src/abaqus/Canvas/ViewportBase.py
Add Viewport.animationController attribute
> Add Viewport.animationController attribute

- src/abaqus/Interaction/ContactExp.py
- src/abaqus/Interaction/InteractionContactControlModel.py
- src/abaqus/Interaction/InteractionModel.py
Add ExpInitialization interaction and add polarityAssignments for ContactExp
> Add ExpInitialization interaction and add polarityAssignments for ContactExp

- src/abaqus/Job/Job.py
> Remove Job.clearMessage for V2016-V2019

- docs/source/reference/mdb/model/material.rst
- src/abaqus/Material/Plastic/Plastic.py
> Add TensileFailure for V2020

- src/abaqus/Part/AcisFile.py
- src/abaqus/Part/AcisMdb.py
> Add Mdb.openSolidworks

- src/abaqus/Odb/OdbSet.py
Add instances and isInternal for OdbSet
> Add instances and isInternal for OdbSet

- src/abaqus/Model/ModelBase.py
- src/abaqus/Step/Step.py
> Add table collections

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2017a8

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2018a8

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2019a8

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2020a8

- src/abaqus/BoundaryCondition/BoundaryConditionModel.py
- src/abaqus/BoundaryCondition/SubmodelBC.py
Add intersectionOnly argument for SubmodelBC
> Add intersectionOnly argument for SubmodelBC

- .readthedocs.yml
Only build html in readthedocs
> Only build html in readthedocs

- src/abaqus/Interaction/ContactExp.py
- src/abaqus/Interaction/ContactPropertyAssignment.py
- src/abaqus/Interaction/ContactStd.py
- src/abaqus/Interaction/InteractionModel.py
- src/abaqus/Interaction/SlidingFormulationAssignment.py
- src/abaqus/Interaction/SurfaceBeamSmoothingAssignment.py
- src/abaqus/Interaction/SurfaceCrushTriggerAssignment.py
- src/abaqus/Interaction/SurfaceFeatureAssignment.py
- src/abaqus/Interaction/SurfaceFrictionAssignment.py
- src/abaqus/Interaction/SurfaceOffsetAssignment.py
- src/abaqus/Interaction/SurfaceThicknessAssignment.py
- src/abaqus/Interaction/SurfaceVertexCriteriaAssignment.py
> Update Interaction APIs

- src/abaqus/Property/CompositePly.py
Update docs of thicknessType and thicknessField for CompositePly
> Update docs of thicknessType and thicknessField for CompositePly

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2021v9

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2016a9

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2017a9

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2018a9

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2019a9

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2020a9

- .github/workflows/pages.yaml
> Build pages in pull requests

- docs/source/reference/mdb/model/material.rst
- src/abaqus/Assembly/AssemblyBase.py
- src/abaqus/Connector/ConnectorDamping.py
- src/abaqus/Connector/ConnectorSection.py
- src/abaqus/Constraint/ConstraintModel.py
- src/abaqus/Constraint/Coupling.py
- src/abaqus/Datum/DatumCsys.py
- src/abaqus/Material/Material.py
- src/abaqus/Material/MaterialBase.py
- src/abaqus/Material/Plastic/CrushStress/CrushStress.py
- src/abaqus/Material/Plastic/CrushStress/CrushStressVelocityFactor.py
- src/abaqus/Material/Plastic/Plastic.py
- src/abaqus/Mesh/ElemType.py
- src/abaqus/Odb/OdbDatumCsys.py
- src/abaqus/Part/PartBase.py
- src/abaqus/Session/SessionBase.py
- src/abaqus/StepOutput/FieldOutputRequest.py
> Add v2022 features

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2016a10

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2017a10

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2018a10

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2019a10

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2020a10

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2021a10

- README.md
- docs/source/conf.py
- meta.yaml
- setup.py
> Update version to v2022a10

- README.md
- docs/source/getting_started.rst
Add doc for installing a specific version
> Add doc for installing a specific version

- src/abaqus/BasicGeometry/CellArray.py
- src/abaqus/BasicGeometry/EdgeArray.py
- src/abaqus/BasicGeometry/IgnoredEdgeArray.py
- src/abaqus/BasicGeometry/IgnoredVertexArray.py
- src/abaqus/Sketcher/ConstrainedSketchGeometry/ConstrainedSketchGeometryArray.py
- src/abaqus/Sketcher/ConstrainedSketchVertex/ConstrainedSketchVertexArray.py
Add return type annotations in the findAt method of object array classes and correct some code blocks
> Add return type annotations in the findAt method of object array classes and correct some code blocks

- src/abaqus/Partition/__init__.py
> Add doc for Partition subpackage

- src/abaqus/OptionsBase.py
- src/abaqus/Print/EpsOptions.py
- src/abaqus/Print/PageSetupOptions.py
- src/abaqus/Print/PngOptions.py
- src/abaqus/Print/PrintOptions.py
- src/abaqus/Print/PsOptions.py
- src/abaqus/Print/SvgOptions.py
> Implement Print Options

- src/abaqus/AbaqusCAEDisplayPreferences/CaeGuiPrefs.py
- src/abaqus/AbaqusCAEDisplayPreferences/CaeKerPrefs.py
- src/abaqus/AbaqusCAEDisplayPreferences/caePrefsAccess.py
> Implement CAE display prederences

- src/abaqus/Animation/AVIOptions.py
- src/abaqus/Animation/AnimationController.py
- src/abaqus/Animation/AnimationOptions.py
- src/abaqus/Animation/AnimationSession.py
- src/abaqus/Animation/ImageAnimation.py
- src/abaqus/Animation/ImageAnimationOptions.py
- src/abaqus/Animation/Movie.py
- src/abaqus/Animation/QuickTimeOptions.py
> Implement Animation

- src/abaqus/CustomKernel/CommandRegister.py
- src/abaqus/CustomKernel/RegisteredDictionary.py
- src/abaqus/CustomKernel/RegisteredList.py
- src/abaqus/CustomKernel/RegisteredTuple.py
- src/abaqus/CustomKernel/RepositorySupport.py
> Implement Registered Objects

- src/abaqus/BasicGeometry/CellArray.py
- src/abaqus/BasicGeometry/EdgeArray.py
- src/abaqus/BasicGeometry/FaceArray.py
- src/abaqus/BasicGeometry/IgnoredEdgeArray.py
- src/abaqus/BasicGeometry/IgnoredVertexArray.py
- src/abaqus/BasicGeometry/VertexArray.py
- src/abaqus/InputFileParser/AbaqusNDarray.py
- src/abaqus/Odb/FieldValueArray.py
- src/abaqus/Sketcher/ConstrainedSketchGeometry/ConstrainedSketchGeometryArray.py
- src/abaqus/Sketcher/ConstrainedSketchVertex/ConstrainedSketchVertexArray.py
- src/abaqus/StepMiscellaneous/RayleighDampingByFrequencyComponentArray.py
- src/abaqus/StepMiscellaneous/StructuralDampingByFrequencyComponentArray.py
- src/abaqus/TableCollection/DataTableArray.py
- src/abaqus/TableCollection/ParameterColumnArray.py
Use type alias for array objects, more for #404
> Use type alias for array objects, more for #404

- .github/release-drafter-v2016.yml
- .github/release-drafter-v2017.yml
- .github/release-drafter-v2018.yml
- .github/release-drafter-v2019.yml
- .github/release-drafter-v2020.yml
- .github/release-drafter-v2021.yml
- .github/release-drafter-v2022.yml
- .github/release-drafter.yml
> Update release drafters

- .github/release-drafter-v2016.yml
- .github/release-drafter-v2017.yml
- .github/release-drafter-v2018.yml
- .github/release-drafter-v2019.yml
- .github/release-drafter-v2020.yml
- .github/release-drafter-v2021.yml
- .github/release-drafter-v2022.yml
- .github/release-drafter.yml
> Update version templates

- src/abaqus/UtilityAndView/AbaqusBoolean.py
- src/abaqus/UtilityAndView/SymbolicConstant.py
- src/symbolicConstants.py
Just update AbaqusBoolean and SymbolicConstants classes with code in the respective modules.
> Update AbaqusBoolean and SymbolicConstants classes

- README-zh-cn.md
- README.md
- docs/source/conf.py
- docs/source/getting_started.rst
- meta.yaml
- setup.py
> Update to v2022.1

- README-zh-cn.md
- README.md
- docs/source/conf.py
- docs/source/getting_started.rst
- meta.yaml
- setup.py
> Update to v2021.1

- README-zh-cn.md
- README.md
- docs/source/conf.py
- docs/source/getting_started.rst
- meta.yaml
- setup.py
> Update to v2020.1

- README-zh-cn.md
- README.md
- docs/source/conf.py
- docs/source/getting_started.rst
- meta.yaml
- setup.py
> Update to v2018.1

- README-zh-cn.md
- README.md
- docs/source/conf.py
- docs/source/getting_started.rst
- meta.yaml
- setup.py
> Update to v2016.1

- README-zh-cn.md
- README.md
- docs/requirements.txt
- docs/source/conf.py
- requirements.txt
- setup.py
- src/abaqus/__init__.py
> Support auto manage version

- .github/release-drafter-v2016.yml
- .github/release-drafter-v2017.yml
- .github/release-drafter-v2018.yml
- .github/release-drafter-v2019.yml
- .github/release-drafter-v2020.yml
- .github/release-drafter-v2021.yml
- .github/release-drafter-v2022.yml
- .github/release-drafter.yml
> Use semantic versioning

- src/abaqus/__init__.py
Fix bugs when _version does not exist
> Fix bugs when _version does not exist

- README-zh-cn.md
- README.md
- docs/source/getting_started.rst
> Update installation guide

- meta.yaml
Manage auto version from Git in Conda
> Manage auto version from Git in Conda

- .github/workflows/python-publish-conda.yml
Checkout tagged version when publishing releases
> Checkout tagged version when publishing releases

- .github/release-drafter-v2016.yml
- .github/release-drafter-v2017.yml
- .github/release-drafter-v2018.yml
- .github/release-drafter-v2019.yml
- .github/release-drafter-v2020.yml
- .github/release-drafter-v2021.yml
- .github/release-drafter-v2022.yml
- .github/release-drafter.yml
Update title of release drafter since auto version is used
> Update title of release drafter since auto version is used

- requirements.txt
Remove setuptools_scm hard requirement
> Remove setuptools_scm hard requirement

- src/abaqus/BasicGeometry/EdgeArray.py
- src/abaqus/BasicGeometry/FaceArray.py
- src/abaqus/BasicGeometry/IgnoredEdgeArray.py
- src/abaqus/BasicGeometry/IgnoredVertexArray.py
- src/abaqus/BasicGeometry/VertexArray.py
- src/abaqus/Calibration/Behavior.py
- src/abaqus/Interaction/InteractionModel.py
- src/abaqus/Material/Plastic/DruckerPrager/Extended/DruckerPragerCreep.py
- src/abaqus/Mesh/MeshAssembly.py
- src/abaqus/Mesh/MeshPart.py
- src/abaqus/Odb/FieldOutput.py
- src/abaqus/Odb/OdbInstanceBase.py
- src/abaqus/Session/Drawing.py
- src/abaqus/Session/SessionBase.py
- src/abaqus/XY/XYSessionBase.py
Update formats of some code blocks, returns, and raises
> Update formats of some code blocks, returns, and raises

- src/abaqus/Interaction/FluidInflator.py
- src/abaqus/Interaction/SlidingFormulationAssignment.py
- src/abaqus/Interaction/SurfaceFrictionAssignment.py
- src/abaqus/Interaction/SurfaceVertexCriteriaAssignment.py
- src/abaqus/Material/Multiscale/MeanFieldHomogenization.py
- src/abaqus/Material/Multiscale/MeanFieldInclusion.py
- src/abaqus/Material/Multiscale/MeanFieldMatrix.py
- src/abaqus/Material/Multiscale/MeanFieldVoid.py
- src/abaqus/Material/Plastic/CrushStress/CrushStress.py
- src/abaqus/PredefinedField/Stress.py
Move the analysis keywords to class notes
> Move the analysis keywords to class notes

- src/abaqus/Material/Multiscale/MeanFieldInclusion.py
- src/abaqus/Material/Multiscale/MeanFieldVoid.py
Update formats of MeanField classes
> Update formats of MeanField classes

- .github/workflows/pytest.yaml
- setup.py
- src/abaqus/__init__.py
> Support Python 3.11

- docs/source/reference/odb.rst
> Add docs for FieldValueArray

- docs/source/reference/odb.rst
Update docs in FieldValueArray
> Update docs in FieldValueArray

- src/abaqus/_decorators.py
Add class suffix for special classes.
Resolve #694, see also #678.
> Add class suffix for special classes

- src/abaqus/_decorators.py
Resolve class suffix.
Resolve #695.
> Resolve class suffix

- .mergify.yml
> Add backport to main

- docs/requirements.txt
- docs/source/conf.py
- src/abaqus/Field/OdbMeshRegionData.py
- src/abaqus/Job/Job.py
- src/abaqus/Job/JobFromInputFile.py
- src/abaqus/Job/ModelJob.py
- src/abaqus/Odb/OdbMeshElement.py
- src/abaqus/PredefinedField/PredefinedFieldModel.py
- src/abaqus/PredefinedField/Stress.py
- src/abaqus/Section/SectionLayer.py
- src/abaqus/Sketcher/ConstrainedSketchDimension/DistanceDimension.py
- src/abaqus/Sketcher/ConstrainedSketchGeometry/ArcByCenterEnds.py
- src/abaqus/Step/GeostaticStep.py
- src/abaqus/Step/StepModel.py
Add V2017 changes notes in the source code and use pydata_sphinx_theme theme, see also #711.
> Add V2017 changes notes in the source code and use pydata_sphinx_theme theme

- src/abaqus/Load/BoltLoad.py
- src/abaqus/Load/LoadModel.py
- src/abaqus/Material/Material.py
- src/abaqus/Material/MaterialBase.py
- src/abaqus/Material/Multiscale/MeanFieldHomogenization.py
- src/abaqus/Material/Multiscale/MeanFieldInclusion.py
- src/abaqus/Material/Multiscale/MeanFieldMatrix.py
- src/abaqus/Material/Multiscale/MeanFieldVoid.py
- src/abaqus/Mesh/MeshElementArray.py
- src/abaqus/Mesh/MesherOptions.py
- src/abaqus/OdbDisplay/ContourOptions.py
- src/abaqus/OdbDisplay/ViewCut.py
- src/abaqus/Part/AcisFile.py
- src/abaqus/Part/PartBase.py
- src/abaqus/PredefinedField/Field.py
- src/abaqus/PredefinedField/FieldState.py
- src/abaqus/PredefinedField/PredefinedFieldModel.py
- src/abaqus/Region/Set.py
- src/abaqus/Section/HomogeneousSolidSection.py
- src/abaqus/Section/SectionModel.py
- src/abaqus/Section/SectionOdb.py
- src/abaqus/Session/Drawing.py
- src/abaqus/Sketcher/ConstrainedSketch.py
- src/abaqus/Step/ExplicitDynamicsStep.py
- src/abaqus/Step/StepModel.py
- src/abaqus/Step/TempDisplacementDynamicsStep.py
- src/abaqus/XY/XYData.py
Add V2018 changes notes in the source code, see also #711.
> Add V2018 changes notes in the source code

- src/abaqus/Assembly/ModelInstance.py
- src/abaqus/DisplayGroup/LeafFromConstraintNames.py
- src/abaqus/Interaction/FluidInflator.py
- src/abaqus/Interaction/FluidInflatorProperty.py
- src/abaqus/Interaction/FluidInflatorState.py
- src/abaqus/Interaction/InteractionModel.py
- src/abaqus/Interaction/InteractionPropertyModel.py
- src/abaqus/Interaction/SurfaceToSurfaceContactStd.py
- src/abaqus/Mesh/ElemType.py
- src/abaqus/OdbDisplay/ContourOptions.py
- src/abaqus/Optimization/BeadTask.py
- src/abaqus/Optimization/OptimizationTask.py
- src/abaqus/Optimization/OptimizationTaskModel.py
- src/abaqus/Optimization/ShapeTask.py
- src/abaqus/Optimization/SizingTask.py
- src/abaqus/Optimization/TopologyOverhangControl.py
- src/abaqus/Optimization/TopologyTask.py
- src/abaqus/PlotOptions/BasicOptions.py
Add V2019 changes notes in the source code, see also #711.
> Add V2019 changes notes in the source code

- src/abaqus/Assembly/AssemblyBase.py
- src/abaqus/Canvas/ViewportBase.py
- src/abaqus/Interaction/ContactExp.py
- src/abaqus/Interaction/ExpInitialization.py
- src/abaqus/Interaction/InteractionContactControlModel.py
- src/abaqus/Interaction/InteractionContactInitializationModel.py
- src/abaqus/Interaction/InteractionModel.py
- src/abaqus/Material/Plastic/TensileFailure.py
- src/abaqus/Model/ModelBase.py
- src/abaqus/Odb/OdbSet.py
- src/abaqus/Part/AcisFile.py
- src/abaqus/Part/AcisMdb.py
- src/abaqus/TableCollection/ActivateElements.py
- src/abaqus/TableCollection/DataTable.py
- src/abaqus/TableCollection/ElementProgressiveActivation.py
- src/abaqus/TableCollection/EventSeries.py
- src/abaqus/TableCollection/EventSeriesType.py
- src/abaqus/TableCollection/ParameterColumn.py
- src/abaqus/TableCollection/ParameterTable.py
- src/abaqus/TableCollection/PropertyTable.py
- src/abaqus/TableCollection/PropertyTableData.py
- src/abaqus/TableCollection/TableCollection.py
- src/abaqus/TableCollection/TableCollectionAssembly.py
- src/abaqus/TableCollection/TableCollectionModel.py
- src/abaqus/TableCollection/TableCollectionStep.py
Add V2020 changes notes in the source code, see also #711.
> Add V2020 changes notes in the source code

- docs/source/reference/mdb/model/interaction.rst
Add references for Fluid Inflator classes
> Add references for Fluid Inflator classes

- docs/source/reference/mdb/model/material.rst
- src/abaqus/BoundaryCondition/BoundaryConditionModel.py
- src/abaqus/BoundaryCondition/SubmodelBC.py
- src/abaqus/Interaction/ContactExp.py
- src/abaqus/Interaction/ContactPropertyAssignment.py
- src/abaqus/Interaction/ContactStd.py
- src/abaqus/Interaction/InteractionModel.py
- src/abaqus/Interaction/SlidingFormulationAssignment.py
- src/abaqus/Interaction/SurfaceBeamSmoothingAssignment.py
- src/abaqus/Interaction/SurfaceCrushTriggerAssignment.py
- src/abaqus/Interaction/SurfaceFrictionAssignment.py
- src/abaqus/Interaction/SurfaceOffsetAssignment.py
- src/abaqus/Interaction/SurfaceThicknessAssignment.py
- src/abaqus/Interaction/SurfaceVertexCriteriaAssignment.py
- src/abaqus/Material/Gap/GapConductance.py
- src/abaqus/Material/Gap/GapConvection.py
- src/abaqus/Material/Gap/GapRadiation.py
- src/abaqus/Material/Material.py
- src/abaqus/Optimization/OptimizationTask.py
- src/abaqus/Optimization/ShapePlanarSymmetry.py
- src/abaqus/Optimization/ShapeRotationalSymmetry.py
- src/abaqus/Property/CompositePly.py
Add V2021 changes notes in the source code, see also #711.
> Add V2021 changes notes in the source code

- src/abaqus/Job/JobFromInputFile.py
Fix versionchanged env of parallelizationMethodExplicit
> Fix versionchanged env of parallelizationMethodExplicit

- src/abaqus/Job/Coexecution.py
Add Coexecution for V2016-V2021
> Add Coexecution for V2016-V2021

- .readthedocs.yml
- setup.py
- src/abaqus/__init__.py
- src/abaqus/_decorators.py
Update default version to 2022.0.0-unknown
> Update default version to 2022.0.0-unknown

- src/abaqus/Interaction/ContactExp.py
- src/abaqus/Interaction/ContactStd.py
- src/abaqus/Interaction/CyclicSymmetry.py
- src/abaqus/Interaction/ExpInitialization.py
- src/abaqus/Interaction/GapHeatGeneration.py
- src/abaqus/Interaction/InteractionModel.py
- src/abaqus/Interaction/PressurePenetration.py
- src/abaqus/Interaction/Radiation.py
- src/abaqus/Interaction/SelfContactStd.py
- src/abaqus/Interaction/StdContactControl.py
- src/abaqus/Interaction/SurfaceToSurfaceContactExp.py
- src/abaqus/Job/Coexecution.py
- src/abaqus/Optimization/DesignDirection.py
- src/abaqus/Optimization/DrillControl.py
- src/abaqus/Optimization/ShapeDemoldControl.py
- src/abaqus/Optimization/ShapePointSymmetry.py
- src/abaqus/Optimization/ShapeRotationalSymmetry.py
- src/abaqus/Optimization/StampControl.py
- src/abaqus/Optimization/TurnControl.py
Fix wrong directives for V2022
> Fix wrong directives for V2022

- src/abaqus/Property/CompositePly.py
> Fix wrong directives for V2021

- src/abaqus/OdbDisplay/ContourOptions.py
- src/abaqus/OdbDisplay/ViewCut.py
- src/abaqus/Step/ExplicitDynamicsStep.py
Fix wrong directives for V2018
> Fix wrong directives for V2018

- src/abaqus/OdbDisplay/ContourOptions.py
Fix wrong directives for V2019
> Fix wrong directives for V2019

- docs/source/reference/mdb/job.rst
> Remove :members: for Job

- .github/workflows/pages.yaml
Revert "Remove pages action, use readthedocs"
> Revert "Remove pages action, use readthedocs"

- README-zh-cn.md
- README.md
- docs/source/index.rst
Add link to the abqpy-translations project
> Add link to the abqpy-translations project

- docs/source/conf.py
> Update locale_dirs in conf.py

- docs/source/conf.py
Change default locale_dirs to locales
> Change default locale_dirs to locales

- .github/workflows/translations.yaml
Push to protected branch when updating translations
> Push to protected branch when updating translations

- .gitignore
Ignore temporary translation files
> Ignore temporary translation files

- .gitignore
> Ignore temporary _version.py

- docs/source/locales/zh_CN/LC_MESSAGES/index.po
> 添加文档主页的简体中文文档

- .gitignore
Update .gitignore to not ignore .pot files
> Update .gitignore to not ignore .pot files

- .github/workflows/translations.yaml
Use github.run_id instead of run_number
> Use github.run_id instead of run_number

- README-zh-cn.md
- README.md
- docs/source/index.rst
> Add Crowdin links

- README-zh-cn.md
- README.md
> Update Crowdin link labels

- README-zh-cn.md
- README.md
> Add pytest badge

- src/abaqus/FieldReport/FieldReportSession.py
- src/abaqus/Interaction/InteractionContactInitializationModel.py
- src/abaqus/Odb/Odb.py
- src/abaqus/Odb/OdbSet.py
- src/abaqus/Odb/OdbStepBase.py
Add ExpInitialization in InteractionContactInitializationModel and Fix wrong formats of code blocks
> Add ExpInitialization in InteractionContactInitializationModel and Fix wrong formats of code blocks

- docs/requirements.txt
- docs/source/conf.py
- docs/source/reference/mdb/model/interaction.rst
Update interaction methods in docs
> Update interaction methods in docs

- src/abaqus/BoundaryCondition/AccelerationBCState.py
- src/abaqus/BoundaryCondition/AccelerationBaseMotionBCState.py
- src/abaqus/BoundaryCondition/AcousticPressureBCState.py
- src/abaqus/BoundaryCondition/ConcentrationBCState.py
- src/abaqus/BoundaryCondition/ConnAccelerationBCState.py
- src/abaqus/BoundaryCondition/ConnDisplacementBCState.py
- src/abaqus/BoundaryCondition/ConnVelocityBCState.py
- src/abaqus/BoundaryCondition/DisplacementBCState.py
- src/abaqus/BoundaryCondition/DisplacementBaseMotionBCState.py
- src/abaqus/BoundaryCondition/ElectricPotentialBCState.py
- src/abaqus/BoundaryCondition/EulerianBCState.py
- src/abaqus/BoundaryCondition/EulerianMotionBCState.py
- src/abaqus/BoundaryCondition/FluidCavityPressureBCState.py
- src/abaqus/BoundaryCondition/MaterialFlowBCState.py
- src/abaqus/BoundaryCondition/PorePressureBCState.py
- src/abaqus/BoundaryCondition/SecondaryBaseBCState.py
- src/abaqus/BoundaryCondition/SubmodelBCState.py
- src/abaqus/BoundaryCondition/TemperatureBCState.py
- src/abaqus/BoundaryCondition/TypeBCState.py
- src/abaqus/BoundaryCondition/VelocityBCState.py
- src/abaqus/BoundaryCondition/VelocityBaseMotionBCState.py
Update docs for the status of boundary condition state classes
> Update docs for the status of boundary condition state classes

- .github/workflows/codeql.yml
- README-zh-cn.md
- README.md
Add LGTM badge and CodeQL workflow
> Add LGTM badge and CodeQL workflow

- docs/source/conf.py
> Update version for docs

- .github/workflows/tests.yaml
- setup.py
Use multiple platforms to build tests
> Use multiple platforms to build tests

- .github/mergify.yml
Use mergify to auto merge backport pull request
> Use mergify to auto merge backport pull request

- src/abaqus/__init__.py
Fix bugs when getting __version__
> Fix bugs when getting __version__

- docs/source/getting_started.rst
> Move ipynbname to the optional requirements in the documentation

- docs/source/conf.py
Add dev suffix in development versions of the documentation
> Add dev suffix in development versions of the documentation

- .github/workflows/release.yml
Add option to publish the release or not, extend #1172.
> Add option to publish the release or not

- .github/workflows/tests.yaml
Fail on warning when building pages
> Fail on warning when building pages

- src/abqpy/decorators.py
Fix bugs of decorators introduced in #1241
> Fix bugs of decorators introduced in #1241

- docs/source/conf.py
- src/abqpy/decorators.py
Fix bugs in getting branch_name when building docs
> Fix bugs in getting branch_name in docs

- src/abaqus/Odb/OdbCommands.py
- src/abaqus/__init__.py
- src/abqpy/abaqus.py
- src/odbAccess.py
Override `mdb.save()` to submit the script, see also #1266 for other possible methods.
> Override `mdb.save()` to submit the script

- README-zh-cn.md
- README.md
- docs/source/index.rst
- docs/source/locales/pot/index.pot
- docs/source/locales/zh_CN/LC_MESSAGES/index.po
Remove `abqpy-translations` links
> Remove `abqpy-translations` links

- src/abqpy/abaqus.py
Fix bugs when getting the main file.
Closes #1286.
> Fix bugs when getting the main file

- .github/workflows/rtd-preview.yml
Add `rtd-preview` workflow
----
:books: Documentation preview :books:: https://abqpy--1304.org.readthedocs.build/en/1304/
----
:books: Documentation preview :books:: https://abqpy-zh-cn--1304.org.readthedocs.build/en/1304/
> Add `rtd-preview` workflow

- .github/mergify.yml
Use default backport pull request title
> Use default backport pull request title

- .github/workflows/release.yml
- .github/workflows/translations.yaml
> Update bot account details

- .github/workflows/release.yml
Add `update` input for `release` workflow
> Add `update` input for `release` workflow

- .github/workflows/release.yml
Fix `inputs.update` error introduced in #1335.
> Fix `inputs.update` error introduced in #1335

- docs/source/tutorials.rst
- examples/compression-output-jupyter.ipynb
- examples/compression-output.py
- tests/test_odb.py
> include `import visualization` module

- .github/mergify.yml
- .github/workflows/translations.yaml
- docs/source/conf.py
Create pull requests when updating translations
> Create pull requests when updating translations

- .github/workflows/translations.yaml
> Add token when creating pull requests for translations

- .github/mergify.yml
- .github/workflows/release.yml
Create pull requests when updating release version
> Create pull requests when updating release version

- .github/mergify.yml
Add branch label for backport pull requests
> Add branch label for backport pull requests

- README-zh-cn.md
- README.md
Requested in #1434 
https://github.com/haiiliin/abqpy/pull/1434#issuecomment-1248882706
> split command lines also in README

- .github/mergify.yml
Make `mergify` auto label rule be consistent
> Make `mergify` auto label rule be consistent

- .github/workflows/tests.yaml
- setup.py
- src/abaqus/Interaction/ContactProperty.py
- src/abaqus/Interaction/FractureCriterion.py
- src/abaqus/Material/Elastic/HyperElastic/ViscoElastic/CombinedTestData.py
- src/abaqus/Material/Eos/Eos.py
- src/abaqus/Material/Material.py
- src/abaqus/Material/Plastic/Concrete/ConcreteCompressionHardening.py
- src/abaqus/Material/Plastic/DruckerPrager/Extended/TriaxialTestData.py
Add PyPy Support and fix some escape sequence warnings
> Add PyPy Support

- docs/source/conf.py
- src/abqpy/template.py
Use `confval` to show template parameters
> Use `confval` to show template parameters

- .github/workflows/tests.yaml
Remove paths in pull_request trigger of tests
> Remove paths in pull_request trigger of tests

- src/abqpy/abaqus.py
> Resolve errors when deciding whether `abqpy` is imported by a file

- docs/source/_static/switcher.json
- docs/source/conf.py
Add version switcher dropdowns
----
:books: Documentation preview :books:: https://abqpy--1692.org.readthedocs.build/en/1692/
> Add version switcher dropdowns

- docs/source/_static/switcher.json
> Fix URL bugs in #1692

- README-zh-cn.md
- README.md
Remove extra badges in READMEs to keep it clean
> Remove extra badges in READMEs to keep it clean

- src/abaqus/__init__.py
To use in interpreter and reading `.rpy` files
> Import python 2 functions into `abaqus` module

- docs/source/conf.py
> Use short version in docs

- .github/workflows/codeql.yml
- .github/workflows/tests.yaml
Update tests workflow trigger conditions
> Update tests workflow trigger conditions

- README-zh-cn.md
- README.md
- setup.py
> Update documentation links

- .github/workflows/docs-test.yml
- .github/workflows/pytest.yml
- README-zh-cn.md
- README.md
> Split tests

- .github/update-suggested-version.py
- docs/source/_static/switcher.json
- docs/source/conf.py
> Update docs links

- .github/workflows/release-drafter.yml
Update pull request types for release drafter
> Update pull request types for release drafter

- .github/PULL_REQUEST_TEMPLATE/pull_request.md
- .github/PULL_REQUEST_TEMPLATE/website.md
- CONTRIBUTING.md
> Add CONTRIBUTING guide

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/pull_request.md
> Update pull request templates

- .github/mergify.yml
- .github/workflows/docs-test.yml
- .github/workflows/docs.yml
Add workflows to generate docs
> Add workflows to generate docs

- .github/workflows/docs.yml
- README-zh-cn.md
- README.md
- docs/source/index.rst
> Fix concurrency issues

- .github/workflows/docs.yml
> Use lowercase in docs version

- .github/workflows/docs.yml
> Fix substring workflow issue

- .github/workflows/docs.yml
- README-zh-cn.md
- README.md
- docs/source/index.rst
Upload docs to different branches
> Upload docs to different branches

- .github/mergify.yml
- .github/workflows/docs.yml
- docs/source/index.rst
> Update docs workflow

- .github/workflows/docs.yml
> Fix wrong docs directory

- docs/source/conf.py
> Handle latest version

- .github/mergify.yml
Not remove the conflicts label
> Not remove the conflicts label

- .github/workflows/docs.yml
- docs/source/conf.py
> Add search box in the sidebar

- .github/workflows/docs-upload.yml
Remove concurrency for docs-upload workflow
> Remove concurrency for docs-upload workflow

- .github/workflows/docs-upload.yml
Use short sha in branch name when uploading docs
Corresponding commit in [haiiliin/docs.abqpy.com/commit/8f3c30a95248eaaa67891918e383078361f30c21](https://github.com/haiiliin/docs.abqpy.com/commit/8f3c30a95248eaaa67891918e383078361f30c21).
> Use short sha in branch name when uploading docs

- .github/workflows/docs-test-backport.yml
- .github/workflows/pytest-backport.yml
- .github/workflows/pytest.yml
- src/abqpy/abaqus.py
Simplify code to decide if it is in debug mode
> Simplify code to decide if it is in debug mode

- .github/workflows/docs-upload.yml
- README-zh-cn.md
- README.md
> Remove Read the Docs badges

- .github/workflows/docs-upload.yml
- docs/source/conf.py
The lastest version will be 2022 instead
Not build docs for the main branch
> Not build docs for the main branch

- docs/source/conf.py
> Remove Ads in the sidebar

- .github/workflows/docs-test-backport.yml
- .github/workflows/docs-test.yml
- docs/source/api.rst
- docs/source/cli.rst
- docs/source/index.rst
- docs/source/references.rst
- docs/source/summary.rst
Combine docs sections because there are too many top-level sections to place in the navigation bar.
> Combine docs sections

- docs/source/api.rst
> Fix cli ref error

- .github/workflows/pytest.yml
> Not build pytest on push

- .github/workflows/docs-upload.yml
- .github/workflows/release.yml
- .github/workflows/translations.yaml
Update the author of the automated pull request
> Update the author of the automated pull request

- docs/source/cli.rst
Fix more indent errors in #2412, first introduced in #2332.
> Fix more indent errors

- .github/workflows/docs-upload.yml
Add concurrency for docs-upload
> Add concurrency for docs-upload

- src/abaqus/BasicGeometry/BasicGeometryPart.py
- src/abaqus/BasicGeometry/InterestingPoint.py
- src/abaqus/Material/Density/Density.py
- src/abaqus/Material/ProgressiveDamageFailure/DamageEvolution.py
- src/abaqus/Material/ProgressiveDamageFailure/DamageInitiation.py
- src/abaqus/Part/Part.py
* Adds new method `InterestingPoint` to `Part` (please, see if it right placed in the folders structure)
* Adds 2 new methods to `DamageInitiation`
> Add new methods

- docs/source/locales/README.md
Fix typo in the README of locales
> Fix typo in the README of locales

- docs/README.md
> Add README for the docs

- .github/workflows/docs-upload.yml
- src/abqpy/abaqus.py
Only upload docs of the dev version on push, other docs will be uploaded when published a release
> Only upload docs of the dev version on push

- .github/workflows/translations.yaml
Update translations once a week
> Update translations once a week

- docs/source/locales/README.md
Fix a typo in the README of locales
> Fix a typo in the README of locales

- .github/workflows/docs-test.yml
- .github/workflows/docs-upload.yml
Fetch all history when build documentation
> Fetch all history when build documentation

- src/abaqus/BasicGeometry/FaceArray.py
- src/abaqus/Feature/Feature.py
Improve type hints/annotations
> Continue to improve type hints

- .github/mergify.yml
Add support for disable backport auto merge
> Add support for disable backport auto merge

- .github/mergify.yml
Support disable backport auto merge for specific versions
> Support disable backport auto merge for specific versions

- .github/workflows/docs-test.yml
Update docs-test pull request trigger
> Update docs-test pull request trigger

- src/abaqus/Mdb/MdbBase.py
Update docstrings in methods of Mdb
> Update docstrings in methods of Mdb

- docs/source/reference/kernel/table_collection.rst
- docs/source/reference/kernel/utility.rst
- docs/source/reference/mdb/model/material.rst
- docs/source/reference/mdb/model/optimization.rst
- docs/source/reference/mdb/model/output.rst
- docs/source/reference/mdb/model/part.rst
- docs/source/reference/mdb/model/part_assembly/engineering.rst
- docs/source/reference/mdb/model/part_assembly/region.rst
- docs/source/reference/mdb/model/predefined.rst
- docs/source/reference/mdb/model/profile.rst
- docs/source/reference/mdb/model/property.rst
- docs/source/reference/mdb/model/section/connector.rst
- docs/source/reference/mdb/model/step.rst
- docs/source/reference/session/canvas.rst
- docs/source/reference/session/field_report.rst
Add `autoclasstoc` for some classes
> Add `autoclasstoc` for some classes

- pyproject.toml
Add toml requirements in pyproject.toml
> Add toml requirements in pyproject.toml

- .github/workflows/docs-test.yml
- docs/requirements.txt
This is a docs preview pull request
----
The pull request for updating the documentation has been created, after the pull request is merged, the documentation will be updated automatically on https://docs.abqpy.com/en/pr-2686 (English) and https://docs.abqpy.com/zh_CN/pr-2686 (Simplified Chinese).
> Docs preview

- .github/workflows/docs-test.yml
- .github/workflows/docs-upload.yml
- docs/source/index.rst
Use haiiliin/action-pull-request-another-repo@v1.0.3 to create pull request
----
The pull request for updating the documentation has been created, after the pull request is merged, the documentation will be updated automatically on https://docs.abqpy.com/en/pr-2750 (English) and https://docs.abqpy.com/zh_CN/pr-2750 (Simplified Chinese).
> Use `haiiliin/action-pull-request-another-repo@v1.0.3` to create pull request

- .github/workflows/docs-test-translations.yml
Separate the test-docs workflow of translations
> Separate the test-docs workflow of translations

- .github/workflows/docs-test-translations.yml
- .github/workflows/docs-test.yml
Update comment of docs preview, changed in #2759.
> Update comment of docs preview

- src/abqpy/abaqus.py
Support script files with spaces in the file name
> Support script files with spaces in the file name

- src/abqpy/__main__.py
- src/abqpy/abaqus.py
Support spaces in file names in the command line interface, Extending #2791.
> Support spaces in file names in the command line interface

- .github/update-suggested-version.py
- docs/source/getting_started.rst
Fix errors when updating the release version
> Fix errors when updating the release version

- docs/requirements.txt
- docs/source/conf.py
Use sphinx-hoverxref to show a floating window on the cross references
----
The pull request for updating the documentation has been created, after the pull request is merged, the documentation will be updated automatically on https://docs.abqpy.com/en/pr-2831.
> Use sphinx-hoverxref to show a floating window on the cross references

- .github/keylabeler.yml
- .github/workflows/docs-test-translations.yml
- .github/workflows/docs-test.yml
- .github/workflows/pytest.yml
> Update workflow names

- docs/source/conf.py
- docs/source/reference/kernel/utility.rst
[docs]: Add `abaqusConstants` module.
> [docs]: Add `abaqusConstants` module

- .github/workflows/docs-test-translations.yml
- .github/workflows/docs-test.yml
- .github/workflows/pytest.yml
Remove the `labeled` type to trigger checks
> Remove the `labeled` type to trigger checks

- .github/keylabeler.yml
- .github/release-drafter-2016.yml
- .github/release-drafter-2017.yml
- .github/release-drafter-2018.yml
- .github/release-drafter-2019.yml
- .github/release-drafter-2020.yml
- .github/release-drafter-2021.yml
- .github/release-drafter-2022.yml
- .github/release-drafter.yml
- .github/workflows/release.yml
- .github/workflows/translations.yaml
[automation]: Update `keylabeler` and release drafter configs
> [automation]: Update `keylabeler` and release drafter configs

- .github/mergify.yml
[automation]: Update mergify rules to auto merge release prs
> [automation]: Update mergify rules to auto merge release prs

- src/abaqus/Material/Material.py
Add `versionadded` note to argument
> [feature]: Add `versionadded` note

- docs/source/conf.py
- src/abqpy/__init__.py
Simplify version in conf.py
----
The pull request for updating the documentation has been created, after the pull request is merged, the documentation will be updated automatically on https://devdocs.abqpy.com/en/pr-2957.
> [docs]: Simplify version in conf.py

- docs/source/conf.py
Fix bugs when abqpy is not installed
> [docs][bug]: Fix bugs when abqpy is not installed

- .github/PULL_REQUEST_TEMPLATE.md
- .github/keylabeler.yml
Update pull request to adopt auto labels
> [automation]: Update pull request to adopt auto labels

- pyproject.toml
- src/abqpy/__init__.py
Update setuptools_scm version_scheme)
> [release] Update setuptools_scm version_scheme

- .github/delete-deleted-files.py
- .github/workflows/delete-deleted-files.yml
Add script to delete conflicted deleted files
> [automation]: Add script to delete conflicted deleted files

- .github/workflows/delete-deleted-files.yml
Delete deleted files on labeled
> [bugfix]: Delete deleted files on labeled

- .github/delete-deleted-files.py
- .github/workflows/delete-deleted-files.yml
Fix the delete-deleted-files workflow
> [bugfix]: Fix the delete-deleted-files workflow

- .github/workflows/delete-deleted-files.yml
> [bugfix][automation]: Fix workflow syntax error

- .github/workflows/delete-deleted-files.yml
Fix delete deleted files errors again
> [automation]: Fix delete deleted files errors again

- .github/workflows/delete-deleted-files.yml
Not change line in the comment
> [automation]: Not change line in the comment

- src/abaqus/Field/AnalyticalField.py
- src/abaqus/Field/OdbMeshRegionData.py
- src/abaqus/Section/SectionLayer.py
Fix unsolved references error in #3019
> [bugfix]: Fix unsolved references error in #3019 (backport #3004)

- src/abaqus/__init__.py
- src/abaqus/builtin.py
> [bugfix]: Refactor imports

- docs/source/conf.py
Append source when building docs
> [docs]: Append source when building docs

- .github/PULL_REQUEST_TEMPLATE.md
Update PULL_REQUEST_TEMPLATE.md
> [automation]: Update PULL_REQUEST_TEMPLATE.md

- .github/PULL_REQUEST_TEMPLATE.md
- .github/keylabeler.yml
- .github/release-drafter-2016.yml
- .github/release-drafter-2017.yml
- .github/release-drafter-2018.yml
- .github/release-drafter-2019.yml
- .github/release-drafter-2020.yml
- .github/release-drafter-2021.yml
- .github/release-drafter-2022.yml
- .github/release-drafter.yml
> [automation]: Add refactor label

- .github/keylabeler.yml
- .github/workflows/black.yml
- pyproject.toml
> [workflow][skip-black]: Add black workflow

- README-zh-cn.md
- README.md
> [docs]: Add screenshots in README

- docs/source/conf.py
> [docs]: Use short version in docs

- .github/PULL_REQUEST_TEMPLATE.md
- .github/mergify.yml
> [automation]: Update mergify workflow

- .github/release-drafter-2016.yml
- .github/release-drafter-2017.yml
- .github/release-drafter-2018.yml
- .github/release-drafter-2019.yml
- .github/release-drafter-2020.yml
- .github/release-drafter-2021.yml
- .github/release-drafter-2022.yml
- .github/release-drafter.yml
Update name template of release drafter
> [automation]: Update name template of release drafter

- README-zh-cn.md
- README.md
> [docs]: Update README links

- docs/source/reference/mdb/model.rst
Remove "Create Models" section in APIs
> [docs]: Remove "Create Models" section in APIs

- docs/source/reference/kernel/utility.rst
> [docs]: Update docs of abaqusConstants

- docs/requirements.txt
- docs/source/conf.py
- docs/source/getting_started.rst
Use grid card in installation methods
> [docs]: Use grid card in installation methods

- .gitignore
- docs/requirements.txt
- docs/source/conf.py
- docs/source/index.rst
- examples/README.rst
- examples/compression-output.py
- examples/compression.py
Add a gallery of examples by sphinx-gallery
----
The pull request for updating the documentation has been created, after the pull request is merged, the documentation will be updated automatically on https://devdocs.abqpy.com/en/pr-3215.
> [docs]: Add a gallery of examples by sphinx-gallery

- docs/source/getting_started.rst
> [docs]: Update getting started

- .gitignore
- docs/source/user/examples/sensitivity.rst
- examples/cantilever.py
- examples/viewerOpenOdbAndContour.py
- examples/viewerPrintContours.py
> [docs]: Add more examples

- .gitignore
- docs/source/getting_started.rst
Use the gif figure in getting started
> [docs]: Use the gif figure in getting started

- .github/workflows/pytest.yml
- pyproject.toml
> [feature]: Support Python 3.11

- src/abaqus/DisplayOptions/GraphicsOptions.py
- src/abaqus/Job/JobFromInputFile.py
- src/abaqus/Job/JobMdb.py
- src/abaqus/Load/BoltLoad.py
- src/abaqus/Load/LoadModel.py
- src/abaqus/Material/evaluateMaterial.py
- src/abaqus/PlotOptions/DisplayOptions.py
> [typing]: Fix some typing annotations

- .github/update-suggested-version.py
Fix filename error when updating version number
> [bugfix]: Fix filename error when updating version number

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/keylabeler.yml
- .github/mergify.yml
- .github/release-drafter-2023.yml
- .github/workflows/black.yml
- .github/workflows/docs-test-translations.yml
- .github/workflows/docs-test.yml
- .github/workflows/pytest.yml
- .github/workflows/release-drafter.yml
- .github/workflows/release.yml
- .github/workflows/translations.yaml
- README-zh-cn.md
- README.md
- docs/source/getting_started.md
> [automation]: Update default branch to 2023
