- src/abaqus/Step/GeostaticStep.py
- src/abaqus/Step/StepModel.py
Add maxNumInc argument for GeostaticStep
> Add maxNumInc argument for GeostaticStep

- src/abaqus/Mesh/ElemType.py
Remove linearKinematicCtrl and initialGapOpening argument in ElemTye for V2016-V2018
> Remove linearKinematicCtrl and initialGapOpening argument in ElemTye for V2016-V2018

- docs/requirements.txt
- docs/source/conf.py
- docs/source/tutorials.rst
Correct typos in the tutorial page and add sphinx extension to make it easy to copy code
> Correct typos in the tutorial page and sphinx extension

- src/abaqus/Region/Set.py
- src/abaqus/Region/Surface.py
Change `Set` and `Surface`'s parent to `Region` to pass sets and surfaces to the `region` argument.
This pull request was originally raised by @Diogo-Rossi in [haiiliin/pyabaqus#18](https://github.com/haiiliin/pyabaqus/pull/18).
Many of the methods are required to provide a region argument, such as:
```python
def BodyCharge(
self,
name: str,
createStepName: str,
region: Region,
magnitude: float,
amplitude: str = UNSET,
distributionType: SymbolicConstant = UNIFORM,
field: str = "",
) -> BodyCharge:
...
```
According to [Abaqus](https://help.3ds.com/2021/English/DSSIMULIA_Established/SIMACAECMDRefMap/simacmd-c-intaclregions.htm?contextscope=all), the `region` argument can be a predefined `Set` object, a predefined `Surface` object, or a temporary `Region` object, to remove warnings of the …
> Change Set and Surface's parent to Region to pass sets and surfaces to the region argument

- meta.yaml
Add setuptools_scm requirement when building conda packages
> Add setuptools_scm requirement when building conda packages

- docs/source/getting_started.rst
Fix Supported Python Versions in Getting Started Pages of the Documentation
> Fix Supported Python Versions in Getting Started Pages of the Documentation

- src/abaqus/_decorators.py
Move links to Abaqus documentation to the note environment.
See also #678.
> Move links to Abaqus documentation to the note environment

- docs/requirements.txt
- docs/source/conf.py
- src/abaqus/Job/Job.py
Change default value for parallelizationMethodExplicit to LOOP and use pydata_sphinx_theme  in V2016, see also #720.
> Change default value for parallelizationMethodExplicit to LOOP and use pydata_sphinx_theme  in V2016

- src/abaqus/CustomKernel/RegisteredDictionary.py
- src/abaqus/CustomKernel/RegisteredList.py
- src/abaqus/CustomKernel/RegisteredTuple.py
- src/abaqus/CustomKernel/RepositorySupport.py
- src/abaqus/Material/Material.py
- src/abaqus/Material/MaterialBase.py
- src/abaqus/Odb/FieldBulkData.py
Fix bugs when abaqus_class_doc is used in the docstrings, introduced in #678.
> Fix bugs when abaqus_class_doc is used in the docstrings

- docs/source/conf.py
Use intersphinx to generate links to the documentation of objects in external projects
> Use intersphinx to generate links to the documentation of objects in external projects

- docs/requirements.txt
- docs/source/conf.py
Use GitPython for the active branch name when getting the source code links of objects
> Use GitPython for the active branch name when getting the source code links of objects

- .github/workflows/tests.yaml
- setup.py
Remove GitHub link in PyPI and rename tests workflow
> Remove GitHub link in PyPI and rename tests workflow

- docs/source/getting_started.rst
> Fix error in using * to match a specific version in the documentation

- src/abaqus/XY/XYData.py
- src/abaqus/XY/XYSession.py
Small pull request making compatible methods of `XYData` and `XYSession` classes.
Solves #1189, from discussion https://github.com/haiiliin/abqpy/discussions/1188
> Correct type annotations and docstrings in `XYData` and `XYSession`

- docs/source/getting_started.rst
- docs/source/tutorials.rst
- src/abaqus/__init__.py
* Make the `noGUI` keyword option the default execution mode in both methods `mdb.saveAs` and `session.openOdb`
* Implement [argument passing](https://help.3ds.com/2022/English/DSSIMULIA_Established/SIMACAEEXCRefMap/simaexc-c-caeproc.htm?contextscope=all&id=30dbc96d9b6c4ac9a12a9b72015b6ee2#simaexc-c-caeproc-t-abqexecprocexample1) to the script.
Fixes #1206 
pytest
**Test Configuration**:
* System version: Windows 10
* Abaqus version: 2021
* Python version: 3.9
* abqpy version: 2021.2.6
> Make `noGUI` keyword option the default execution mode and implement argument passing

- tests/conftest.py
- tests/test_mdb.py
- tests/test_odb.py
Use pytest_configure to insert the source code to sys.path before executing pytest, see also
> This is quite complicated, how about use the `pytest_configure` function in the `conftest.py` file (https://stackoverflow.com/a/53690092)? 
> ```python
> # tests/conftest.py
> def pytest_configure(config):
>     os.system('pip install ..')
> ```
> 
> _Originally posted by @haiiliin in https://github.com/haiiliin/abqpy/pull/1104#discussion_r965562206_
> Use pytest_configure to insert the source code to sys.path before executing pytest

- .github/workflows/tests.yaml
Use Python 3.11.0-rc.2 to Build Tests
> Use Python 3.11.0-rc.2 to Build Tests

- .github/mergify.yml
Use squash as default method for mergify automerge
Already done in ba8405053b7e407906d7731f8dab97f6f2ab6804, but not backport to V2016-V2022.
> Use squash as default method for mergify automerge

- .github/mergify.yml
Remove mergify rule for removing `conflicts` label, not applicable for backport pull requests with conflicts.
> Remove mergify rule for removing `conflicts` label

- docs/source/reference/session.rst
- src/abaqus/Canvas/CanvasSession.py
- src/abaqus/Canvas/ViewportBase.py
- src/abaqus/Session/Session.py
- src/abaqus/Session/SessionBase.py
- src/visualization.py
The `Viewport()` method was missing in the `session` object
```python
session.Viewport
```
This method is executed in `abaqus.rpy` file
I named its parent's class as `CanvasSession`, but didn't find a `Session Object` in Canas documentation. Feel free to change.
Additionally, change the initialization of `session.viewports['Viewport: 1']` to the `visualization` module
> Add viewport method to session

- src/odbAccess.py
Possible solution to correct issue in running odbAccess (`cae=False`) before importing `abaqus` (witch runs `cae=True`)
Fixes #1549
> Move line with `run()` function to before `import abaqus`

- src/abaqus/__init__.py
- src/abqpy/abaqus.py
- src/abqpy/python2funcs.py
* Removing some static type checker warnings. [55831bc](https://github.com/haiiliin/abqpy/pull/1567/commits/55831bc769bccc660f9a35ebc1cd7c8ce38a3e42)
* Add some functions compatible with python 2, to not raise errors erros and warnings when used inside the scripts ([6688357](https://github.com/haiiliin/abqpy/pull/1567/commits/6688357e495ea965806bcd3b076506a848a576f1), [eb9e35b](https://github.com/haiiliin/abqpy/pull/1567/commits/eb9e35b13a3efd04bd4627e80efe6da12d4aad84))
* Some warnings raised inside the file `abaqus.rpy`. [38636a0](https://github.com/haiiliin/abqpy/pull/1567/commits/38636a0a221f60acc582b5a03d142cc172eb3896)
> Remove some static type check warnings

- src/abqpy/abaqus.py
When the `abqpy` is not imported by a python file, i.e., by the python console, the `__main__.__file__` is None, an `AttributeError` will be raised, and this pull request solves this problem.
> Fix errors when not executed by a python file

- src/abaqus/UtilityAndView/SymbolicConstant.py
This change is made in attempt to preserve the name space of the "abaqusConstants" when the type is show.
Before the change, users may think that the name space of the constants is `SymbolicConstants`, (because of the `Enum` class name) which is wrong.
After the change, the name space of constants appears as `abaqusConstants`, as the original intention.
> Change class name and make type alias to preserve name space

- src/abqpy/__main__.py
Improves implementation of abaqus command line arguments, discussed in #1269
This change should be backported to the previous releases:
> Handle command line arguments

- .github/workflows/conda.yml
- .github/workflows/pypi.yml
Fix syntax error for 2016 and 2017 introduced in #2280 and #2281
> Fix syntax error for 2016 and 2017

- .github/workflows/docs-test-backport.yml
- .github/workflows/docs-test.yml
- .github/workflows/pytest-backport.yml
- .github/workflows/pytest.yml
> Remove concurrency

- .github/workflows/docs-test-backport.yml
- .github/workflows/docs-test.yml
- src/abaqus/Feature/Feature.py
Correct type annotations of `PartitionCellByPlanePointNormal`
> Annotations of method `PartitionCellByPlanePointNormal`

- .github/workflows/docs-test-backport.yml
- .github/workflows/docs-test.yml
- .github/workflows/pytest-backport.yml
Not use the branch name for GitHub actions
> Not use the branch name for GitHub actions

- src/abqpy/abaqus.py
Simplify the condition check to remove Pylance warning.
This change should be backported to the previous releases:
> Modify check if is running by file

- src/abaqus/BasicGeometry/CellArray.py
- src/abaqus/BasicGeometry/EdgeArray.py
- src/abaqus/Section/SectionModel.py
Correct type hints in `CellArray` `EdgeArray` modules
> Correct type hints in `CellArray` `EdgeArray` modules

- src/abaqus/BasicGeometry/CellArray.py
- src/abaqus/BasicGeometry/EdgeArray.py
- src/abaqus/Region/RegionPart.py
Change the `findAt` method again.
Now there are 3 overloads:
* If `coordinates` is a tuple of floats, the function returns a single instance.
This was inspected in Abaqus/CAE cli. Any other situation returns a list of instances.
* If `coordinates` is a single tuple of tuples of floats, the function returns  a list of instances
In this case, `coordinates` can be passed as keyword, or single positional.
This is the case of the [test](https://github.com/haiiliin/abqpy/blob/99d1c9dc1264c319b11b862c225eff4c090698be/tests/test_mdb.py#L20) file.
* If `coordinates` is omitted and and many positional arguments are passed (tuples of tuples of floats), 
the function returns  a list of instances.
This is the case of example in docstring.
```python
@overload
@abaqus_method_doc
def findAt(
self, …
```
> Correct overloads for `findAt` again

- src/abaqus/Feature/Feature.py
Accepts single cell in method `PartitionCellByPlanePointNormal`
> Accepts single cell

- .gitignore
- src/abqpy/__main__.py
- src/abqpy/abaqus.py
This PR adds a alternative way to change the abaqus execution options.
It allows to change the options at run time, setting a environment variable `ABAQUS_COMMAND_OPTIONS`
Useful to change the options directly in the code.
```python
import os
os.environ['ABAQUS_COMMAND_OPTIONS'] = str({'noGUI': False, 'database':'file.odb'})
from abaqus import *
...
```
It also uniforms the way the command is executed, making it similar to the `abqpy` command line interface.
Relates to #1269 
> Alternative abaqus execution option

- src/part.py
This PR proposes to add the `mdb` and `abaqusConstants` to `part` module.
```python
import displayGroupMdbToolset
from abaqus import mdb
from abaqusConstants import *
```
The reasons for that is:
* to allow *journal* files (`.jnl`) to run directly
* to let the IDE identifies `mdb` and constant values in the `.jnl` file
Because it does not import `abaqus` neither `abaqusConstants` by default:
```python
from part import *
from material import *
from section import *
from assembly import *
from step import *
from interaction import *
from load import *
from mesh import *
from optimization import *
from job import *
from sketch import *
from visualization import *
from connectorBehavior import *
mdb.models['Model-1'].ConstrainedSketch(name='sketch', sheetSize=1.0) …
```
> Add `mdb` and constants to `part` module

- src/abaqus/BasicGeometry/CellArray.py
- src/abaqus/BasicGeometry/EdgeArray.py
- src/abaqus/BasicGeometry/FaceArray.py
- src/abaqus/BasicGeometry/IgnoredEdgeArray.py
- src/abaqus/BasicGeometry/IgnoredVertexArray.py
- src/abaqus/BasicGeometry/VertexArray.py
- src/abaqus/Mesh/MeshEdgeArray.py
- src/abaqus/Mesh/MeshElementArray.py
- src/abaqus/Mesh/MeshFaceArray.py
- src/abaqus/Mesh/MeshNodeArray.py
- src/abaqus/Sketcher/ConstrainedSketchGeometry/ConstrainedSketchGeometryArray.py
- src/abaqus/Sketcher/ConstrainedSketchVertex/ConstrainedSketchVertexArray.py
* Correct type hints of `getSequenceFromMask` method
* Correct remaining `findAt` methods
* Format doc strings
> Correct some methods

- src/abaqus/Mdb/MdbBase.py
- src/abaqus/Mesh/MeshElement.py
- src/abaqus/Mesh/MeshPart.py
- src/abaqus/Region/RegionAssembly.py
Correct some types on the following modules:
* `MeshElement.py`
* `RegionAssembly.py`
* `MeshPart.py`
* `MdbBase.py`
Implements #2782 
> [Typing] Correct types in some modules

- src/abaqus/Amplitude/AmplitudeModel.py
- src/abaqus/Amplitude/TabularAmplitude.py
- src/abaqus/BasicGeometry/Edge.py
- src/abaqus/BasicGeometry/Vertex.py
- src/abaqus/Feature/Feature.py
- src/abaqus/Job/JobFromInputFile.py
- src/abaqus/Job/JobMdb.py
- src/abaqus/Mesh/MeshElementArray.py
- src/abaqus/Part/Part.py
This PR adds some parameters and method that are inferred from command recording in Abaqus, i.e., not explicit in the documentation.
In `JobFromInputFile` method:
* arguments `queue` and `atTime` can accept `None`
* New arguments: `getMemoryFromAnalysis`, `numGPUs` and `resultsFormat` inferred from command
Other changes:
* New method `insertElements` in `Part` class (inferred from command)
* Improve type annotations by adding Literal constants
* Avoid circular imports
* Improve type hints
> [typing][feature]: Add infer from cmd recording

- .github/workflows/release-drafter.yml
Update release drafter on push
> [automation]: Update release drafter on push

- src/abqpy/__main__.py
- src/abqpy/abaqus.py
The command parsed to `abaqus` should be
```sh
abaqus cae script="path/to/file.py"
```
not
```sh
abaqus cae "script=path/to/file.py"
```
This PR corrects that.
> [bugfix]: Correct support to spaces in file names

- .github/workflows/release-news.yml
Add workflow to trigger release news
> [workflow]: Add workflow to trigger release news

- .github/workflows/wheels.yml
> [automation]: Upload wheels on release

- .github/PULL_REQUEST_TEMPLATE.md
- .github/keylabeler.yml
> [docs]: Add `docs preview` to labeler

- .github/PULL_REQUEST_TEMPLATE.md
- .github/keylabeler.yml
- .github/workflows/black.yml
Only reformat the code when the `reformat-with-black` label is added
> [automation]: Only reformat the code when `reformat-with-black` label is added

- .github/workflows/release.yml
Disable auto merge for update release version
> [automation]: Disable auto merge for update release version
